# Site settings
title: Cognitive Science & AI Research Group
description: > # this means to ignore newlines until "baseurl:"
  <b>Tilburg CS & AI Group</b><br>
  Dante Building<br>
  5037 AB Tilburg<br>
  013 466 2140
repository: https://github.com/tcsai/tcsai.github.io

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown

# Customizations
your_name: CS & AI
email: ourmail@uvt.nl

navigation:
  - text: Home
    url: /
  - text: People
    url: /people
  - text: Publications
    url: /pub
  - text: Blogs
    url: /blogs
  - text: Software
    url: /code
  - text: Teaching
    url: /edu

courses:
  - name: Social Data Mining
    teachers: Postma, E., Chrupała, G., Emmery, C.
    description: Data Science methods are becoming the main tools for acquiring information both in the business context and in scientific research. The course offers a thorough introduction to the use of data mining for the analysis of data in a wide variety of formats. Upon completion of the course, students will have acquired the skills necessary to apply data mining in support of decision making, visualisation, and discovery. In addition, students will be familiar with advanced topics such as deep learning. The perspective of the course is application-oriented and serves to provide students with the knowledge and experience that is in line with the current demand for skilled data scientists.
    image: http://www.healthbizdecoded.com/wp-content/uploads/2013/06/data-mining-630x390.jpg
    link: https://mystudy.uvt.nl/it10.vakzicht?taal=N&pfac=FGW&vakcode=880091
  - name: Machine Learning
    teachers: Chrupała, G., Noord van, N.
    description: Learning from examples is one of the most basic aspects of human intelligence. The field of Machine Learning tries to replicate this skill and apply it to real-world problem; filtering spam from your mailbox, recognizing faces in photos, classifying documents, recommending movies and songs, or detecting credit-card fraud. In this course you will learn the theory behind classic machine learning algorithms and at the same time get hands-on experience with using the programming language Python to apply machine learning methods to practical problems.
    image: https://jaxenter.com/wp-content/uploads/2015/03/shutterstock_155844119-e1426582475771.jpg
    link: https://mystudy.uvt.nl/it10.vakzicht?taal=e&pfac=FGW&vakcode=880083
  - name: Research Skills - Text Mining
    teachers: Engelen, J., Keuleers, E., Emmery, C.
    description: Do liars use specific words and sentence structures more often than people who tell the truth? Can a computer judge the quality of a text and make suggestions for improvement? Have political speeches become more polarizing in the last decade? How can a publisher turn a newspaper archive with millions of articles into an online database that can be browsed by topic? These are just a few questions that fall within the scope of ‘text mining’, an umbrella term for various processes for extracting high-quality information from text, mostly relying on advanced computational techniques.
    image: http://thehackednews.com/wp-content/uploads/2016/05/stock-photo-robot-child-reading-a-book-in-the-workshop-of-its-creator-287641082-810x541.jpg
    link: https://mystudy.uvt.nl/it10.vakzicht?taal=e&pfac=FGW&vakcode=880022

software:
  - name: Omesa
    authors: Emmery, C.
    link: https://github.com/cmry/omesa
    language: Python
    description: Framework for reproducable Text Mining research.
  - name: funktional
    authors: Chrupała, G.
    language: Python
    description: A minimalistic toolkit for functionally composable neural network layers with Theano.

people:
  - name: Dr. Afra Alishahi
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/507532.jpg
    description: My primary research interest involves the development of computational models of human language acquisition. Computational modeling is an effective tool for studying human cognitio; whereas linguistic and psychological theories often give a high level explanation for the experimental data, computational models provide a detailed account of the underlying mechanisms for the cognitive task at hand. Moreover, the behavior of a model can be directly compared to that of humans through computational simulation.
    contact: mail@tilburguniversity.edu
  - name: Dr. Grzegorz Chrupała
    image: http://grzegorz.chrupala.me/me.jpg
    description: Discovering structure in text. With the advent of digital storage large and increasing quantities of text are being recorded every day. In order to make sense of this continuing stream of data I am working on computational methods for discovering meaningful structure in it. My main focus is on cognitively-inspired models of language learning which illuminate language acquisition in humans while at the same time being useful for real-world text understanding applications.
    contact: mail@tilburguniversity.edu
  - name: Chris Emmery
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/xy.jpg
    description: I’m a Lecturer at Tilburg University, as well as a joint PhD candidate doing research for both the CS&AI group at Tilburg and CLiPS at the University of Antwerp under the supervision of Eric Postma, Grzegorz Chrupała, and Walter Daelemans. I currently teach Text Mining and Social Data Mining in context of the new Data Science master. Before, I worked for the AMiCA project where my research was mainly in the field of Text Mining. During this, I focussed on applying Machine Learning for forensic and online security-related applications such as detection of cyberbullying and child grooming, and author profiling. On top of this, I developed software to apply these techniques on social media.
    contact: c.d.emmery@uvt.nl
  - name: Ákos Kádár
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/kadar.jpg
    description: I am a PhD student at TiCC working in the field of Computational Modeling of Human Language Acquisition. My primary focus is on learning grounded meaning representations of linguistic units at various levels, from word level to larger multi-word constructions. In my work I borrow methods from both Computer Vision and Computational Linguistics to leverage information from word-word and word-image co-occurences to approximate the meanings of linguistic expressions. I am mostly interested in constructing and evaluating computational models that do not distinguish between the representation of words and visual information and aim to explain how concepts and linguistic meanings arise from these sources.
    contact: a.kadar@uvt.nl
  - name: Prof.dr. Max Louwerse
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/m.m.louwerse.jpg
    description: Max Louwerse is Professor of Cognitive Psychology and Artificial Intelligence at Tilburg University. After his PhD from the University of Edinburgh, Scotland, he was Assistant Professor, Associate Professor and Full Professor in Psychology at the Institute for Intelligent Systems at the University of Memphis, and Director of the Institute for Intelligent Systems. He served as Principal Investigator, Co-Principal Investigator or Senior Researcher on over 10 millions dollar of federally funded grant projects and published over 100 articles in the cognitive sciences, including publications on symbolic and embodied cognition, language statistics, multimodal communication, embodied conversational agents, cohesion and coherence, and discourse processes.
    contact: mail@tilburguniversity.edu
  - name: Prof.dr. Eric Postma
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/370030.jpg
    description: My main research focuses on the automatic analysis of visual and vocal expressions and behaviors by means of methods from the domains of Social Signal Processing and Affective Computing. Human perceptual and cognitive mechanisms serve as an inspiration for the development of these methods. In addition, I study the automatic classification and analysis of visual texture and color to determine the authorship of paintings.
    contact: mail@tilburguniversity.edu
  - name: Dr. Marie Postma
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/720333.jpg
    description: As shown in a number of psychoacoustic and neurological studies, human listeners differ in what aspects of a complex sound signal they perceive to be dominant. In particular, they can be roughly divided between F0 listeners, who focus on the information encoded in the fundamental frequency and its change in time, and spectral listeners, who are primarily affected by the overall spectral information in the signal, such as its timbre. Given that discriminating the individual components of the sound signal is the core skill behind human speech processing, it is of importance that we gain insight into individual differences in speech perception and their possible impact on interpretation, as well as on production and language learning.
    contact: mail@tilburguniversity.edu
  - name: Dr. Sander Wubben
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/143286.jpg
    description: My research focuses on automatic monolingual text-to-text generation. Examples of monolingual text-to-text generation are paraphrase generation, sentence simplification, sentence compression and language transformation. The ability to paraphrase can serve to explain something or to provide feedback in dialogue. Sentence compression is useful for generating summaries, subtitles or tweets. Language transformation can be used to make text written in for example Middle Dutch accessible by transforming it to modern day language. Text-to-text generation may also help to increase performance of other natural language processing tasks such as question answering, dialogue systems and machine translation. In my research I regard text-to-text generation as a monolingual machine translation task and I investigate how machine translation methods can be applied to monolingual text-to-text generation.
    contact: mail@tilburguniversity.edu
  - name: Dr. Menno van Zaanen
    image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/289667.jpg
    description: Many sources of data, such as natural language or music, have an inherent internal structure. This structure describes the regularities and restrictions of the data. This research aims at making the structure explicit, which leads to a description of the underlying (formal) language of the data. This information can then be used, for instance, to group similar elements in the data together. The research is divided into two parts. The first part aims at learning language models that describe the data and can be used to introduce explicit structure on top of the unstructured data. The second part aims at using the identified structure in specific applications. For instance, in the context of mood classification of (music) lyrics, language models for each of the different moods can be used to identify the underlying mood of the lyrics of a particular song. Similarly, language models can be applied within spelling correction systems that require sentential context to identify and correct errors.
    contact: mail@tilburguniversity.edu

social:
  - service: github
    username: tcsai
    link: https://github.com/tcsai
  - service: twitter
    username: _tcsai
    link: https://twitter.com/_tcsai
  - service: rss
    username: rss
    link: ./feed.xml

# Plugins
gems:
  - jekyll-seo-tag
