# Site settings
title: Cognitive Science & AI Research Group
description: > # this means to ignore newlines until "baseurl:"
  <b>Tilburg CS & AI Group</b><br>
  Dante Building<br>
  5037 AB Tilburg<br>
  013 466 2140
repository: https://github.com/tcsai/tcsai.github.io

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown

# Customizations
your_name: CS & AI
email: ourmail@uvt.nl

navigation:
  - text: Home
    url: /
  - text: People
    url: /people
  - text: Publications
    url: /pub
  - text: Blogs
    url: /blogs
  - text: Software
    url: /code
  - text: Teaching
    url: /edu
  - text: Social
    url: /soc

courses:
  - name: Social Data Mining
    teachers: Postma, E., Chrupała, G., Emmery, C.
    bb: https://mystudy.uvt.nl/it10.vakzicht?taal=N&pfac=FGW&vakcode=880091
    git: https://github.com/tcsai/social-data-mining
  - name: Machine Learning
    teachers: Chrupała, G., Noord van, N.
    bb: https://mystudy.uvt.nl/it10.vakzicht?taal=e&pfac=FGW&vakcode=880083
  - name: Research Skills - Text Mining
    teachers: Engelen, J., Keuleers, E., Emmery, C.
    bb: https://mystudy.uvt.nl/it10.vakzicht?taal=e&pfac=FGW&vakcode=880022
    git: https://github.com/tcsai/text-mining

software:
  - name: Omesa
    authors: Emmery, C.
    link: https://github.com/cmry/omesa
    language: Python
    description: Framework for reproducable Text Mining research.
  - name: funktional
    authors: Chrupała, G.
    language: Python
    description: A minimalistic toolkit for functionally composable neural network layers with Theano.

staff:
    - director:
      label: Directors
      people:
      - name: Prof.dr. Max Louwerse
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/m.m.louwerse.jpg
        plink: m.m.louwerse

      - name: Prof.dr. Eric Postma
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/370030.jpg
        plink: e.o.postma

    - scientificstaff:
      label: Scientific staff
      people:
      - name: Prof. Pieter Spronck
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/447823.jpg
        plink: p.spronck

      - name: Dr. Afra Alishahi
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/507532.jpg
        plink: a.alishahi

      - name: Dr. Grzegorz Chrupała
        image: http://grzegorz.chrupala.me/me.jpg
        plink: g.chrupala

      - name: Dr. Marie Postma
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/720333.jpg
        plink: marie.postma

      - name: Dr. Menno van Zaanen
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/289667.jpg
        plink: m.m.vanzaanen

      - name: Chris Emmery
        image: https://avatars3.githubusercontent.com/u/6041070?v=3&s=460
        website: https://cmry.nl
        email: c.d.emmery@uvt.nl
        other:
          - icon: github
            link: https://github.com/cmry
          - icon: twitter
            link: https://twitter.com/_cmry

    - postdocs:
      label: Postdocs
      people:
      - name: Dr. Sander Wubben
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/143286.jpg
        plink: s.wubben

    - phds:
      label: PhDs
      people:

      - name: Ákos Kádár
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/kadar.jpg
        plink: a.kadar

      - name: Nanne van Noord
        image: https://lyrawww.uvt.nl/~meetourstaff/imgs/dci/noord.jpg
        website: http://nanne.github.io/

    - researchassistants:
      label: Research assistants
      people:

social:
  - service: github
    username: tcsai
    link: https://github.com/tcsai
  - service: twitter
    username: _tcsai
    link: https://twitter.com/_tcsai
  - service: rss
    username: rss
    link: ./feed.xml

# Plugins
gems:
  - jekyll-seo-tag
